FROM openjdk:8
COPY ./target/authorization-server-0.0.1-SNAPSHOT.jar authorization-server-0.0.1-SNAPSHOT.jar
COPY ./wait-for-it.sh wait-for-it.sh 
RUN chmod +x wait-for-it.sh
CMD ["./wait-for-it.sh" , "gateway-server:8765" , "--strict" , "--timeout=125" , "--" , "java", "-jar", "authorization-server-0.0.1-SNAPSHOT.jar"]